### ISSUE TITLE
ScrollContainers sometimes don't work for reasons unknown

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3121]
I have tried every which way to make docking ports use a scrollcontainer but somehow it just doesn't work. I cross-referenced it to admin logs and they look identical. It's the only control I can't figure out where sometimes it's not visible and is flat entirely.

![image](https://user-images.githubusercontent.com/31366439/184061202-58126078-db26-4e02-a506-435c53469eec.png)

IDK if I'm doing something wrong but I'm not alone in trying to decipher this blackbox.

**Comment by wrexbe** [comment]
Maybe I fixed this in the pending UI refactor?
https://github.com/space-wizards/RobustToolbox/pull/2712/commits/16044bed39823e9caa06bda2b18f2e014863e29b#diff-a2128b9f175cdb224f8191abea2925c77e7bba079213ec154e342f3078747bc7

**Comment by metalgearsloth** [comment]
Still an issue in 2024 and extremely difficult to even get working.

**Comment by PJB3005** [comment]
Is this like a first-frame glitch or?

**Comment by metalgearsloth** [comment]
It just doesn't show most of the time I try to use it and it's the only control I have ongoing problems with:

![image](https://github.com/space-wizards/RobustToolbox/assets/31366439/1e566aff-66bc-41f2-aa6b-0b531fa7be3a)

![image](https://github.com/space-wizards/RobustToolbox/assets/31366439/d8734cf4-7542-4ca1-ba1f-8ad93249697b)

(The BoxContainer itself having a collapsible control under it).
